[package]
name = "functional-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
functional-syn = { version = "=1.0.83", path = "../functional-syn" }
proc-macro2 = "1.0"
quote = "1.0"
rand = "0.8.4"
